// Code generated by golex. DO NOT EDIT.

package parser

import (
	"fmt"
	"io"
	"strconv"
)

type lexer struct {
	source io.Reader
	/*
	 * The golex used by us can not construct yytext when we reached an accepting state,
	 * so we construct it by ourself. `buf` plays same role as yytext, the invocation of
	 * next() means that `current` was accepted, so we push it to `buf`, when we enter
	 * execution of action, yytext is saved in `buf`.
	 */
	buf     []byte /* used to save token */
	current byte

	insts []AddressedInst
}

func newLexer(src io.Reader) *lexer {
	l := &lexer{source: src}
	l.next()
	return l
}

func (this *lexer) Error(e string) {
	fmt.Printf("error happens in parser: %s\n", e)
	return
}

func (this *lexer) next() byte {
	if this.current != 0 {
		this.buf = append(this.buf, this.current)
	}
	this.current = 0
	var b [1]byte
	if ret, _ := this.source.Read(b[:]); ret > 0 {
		this.current = b[0]
	}
	return this.current
}

func (this *lexer) Lex(lval *yySymType) int {

yystate0:

	this.buf = this.buf[:0]

	goto yystart1

yystate1:
	this.next()
yystart1:
	switch {
	default:
		goto yyabort
	case this.current == '#':
		goto yystate5
	case this.current == '*':
		goto yystate7
	case this.current == '+':
		goto yystate8
	case this.current == ',':
		goto yystate9
	case this.current == '-':
		goto yystate10
	case this.current == '0':
		goto yystate11
	case this.current == '1':
		goto yystate14
	case this.current == '2':
		goto yystate15
	case this.current == '4':
		goto yystate16
	case this.current == '8':
		goto yystate17
	case this.current == ':':
		goto yystate18
	case this.current == '<':
		goto yystate19
	case this.current == 'B':
		goto yystate22
	case this.current == 'D':
		goto yystate30
	case this.current == 'F':
		goto yystate39
	case this.current == 'O':
		goto yystate48
	case this.current == 'Q':
		goto yystate57
	case this.current == 'T':
		goto yystate66
	case this.current == 'W':
		goto yystate75
	case this.current == 'X':
		goto yystate83
	case this.current == 'Y':
		goto yystate94
	case this.current == 'Z':
		goto yystate105
	case this.current == '[':
		goto yystate116
	case this.current == '\n':
		goto yystate4
	case this.current == '\t' || this.current == '\r' || this.current == ' ':
		goto yystate3
	case this.current == '\x00':
		goto yystate2
	case this.current == ']':
		goto yystate117
	case this.current == 'a':
		goto yystate118
	case this.current == 'b':
		goto yystate123
	case this.current == 'c':
		goto yystate135
	case this.current == 'd':
		goto yystate140
	case this.current == 'e':
		goto yystate147
	case this.current == 'f':
		goto yystate166
	case this.current == 'g':
		goto yystate168
	case this.current == 'l':
		goto yystate171
	case this.current == 'm':
		goto yystate175
	case this.current == 'r':
		goto yystate185
	case this.current == 's':
		goto yystate239
	case this.current == 'x':
		goto yystate245
	case this.current == 'y':
		goto yystate281
	case this.current == 'z':
		goto yystate317
	case this.current >= 'h' && this.current <= 'k' || this.current >= 'n' && this.current <= 'q' || this.current >= 't' && this.current <= 'w':
		goto yystate170
	}

yystate2:
	this.next()
	goto yyrule24

yystate3:
	this.next()
	switch {
	default:
		goto yyrule219
	case this.current == '\t' || this.current == '\r' || this.current == ' ':
		goto yystate3
	}

yystate4:
	this.next()
	goto yyrule12

yystate5:
	this.next()
	switch {
	default:
		goto yystate5 // this.current >= '\x01' && this.current <= '\t' || this.current >= '\v' && this.current <= 'ÿ'
	case this.current == '\x00' || this.current == '\n':
		goto yystate6
	}

yystate6:
	goto yyrule217

yystate7:
	this.next()
	goto yyrule16

yystate8:
	this.next()
	goto yyrule14

yystate9:
	this.next()
	goto yyrule19

yystate10:
	this.next()
	goto yyrule15

yystate11:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'X' || this.current == 'x':
		goto yystate12
	}

yystate12:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'f':
		goto yystate13
	}

yystate13:
	this.next()
	switch {
	default:
		goto yyrule11
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'f':
		goto yystate13
	}

yystate14:
	this.next()
	goto yyrule20

yystate15:
	this.next()
	goto yyrule21

yystate16:
	this.next()
	goto yyrule22

yystate17:
	this.next()
	goto yyrule23

yystate18:
	this.next()
	goto yyrule13

yystate19:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == '>':
		goto yystate20
	case this.current >= '\x01' && this.current <= '\t' || this.current >= '\v' && this.current <= '=' || this.current >= '?' && this.current <= 'ÿ':
		goto yystate19
	}

yystate20:
	this.next()
	switch {
	default:
		goto yyrule218
	case this.current == ':':
		goto yystate21
	}

yystate21:
	this.next()
	switch {
	default:
		goto yyrule218
	}

yystate22:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'Y':
		goto yystate23
	}

yystate23:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate24
	}

yystate24:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'E':
		goto yystate25
	}

yystate25:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate26
	}

yystate26:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate27
	}

yystate27:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate28
	}

yystate28:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate29
	}

yystate29:
	this.next()
	goto yyrule1

yystate30:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'W':
		goto yystate31
	}

yystate31:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'O':
		goto yystate32
	}

yystate32:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate33
	}

yystate33:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'D':
		goto yystate34
	}

yystate34:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate35
	}

yystate35:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate36
	}

yystate36:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate37
	}

yystate37:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate38
	}

yystate38:
	this.next()
	goto yyrule2

yystate39:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'W':
		goto yystate40
	}

yystate40:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'O':
		goto yystate41
	}

yystate41:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate42
	}

yystate42:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'D':
		goto yystate43
	}

yystate43:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate44
	}

yystate44:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate45
	}

yystate45:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate46
	}

yystate46:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate47
	}

yystate47:
	this.next()
	goto yyrule3

yystate48:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'W':
		goto yystate49
	}

yystate49:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'O':
		goto yystate50
	}

yystate50:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate51
	}

yystate51:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'D':
		goto yystate52
	}

yystate52:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate53
	}

yystate53:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate54
	}

yystate54:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate55
	}

yystate55:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate56
	}

yystate56:
	this.next()
	goto yyrule4

yystate57:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'W':
		goto yystate58
	}

yystate58:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'O':
		goto yystate59
	}

yystate59:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate60
	}

yystate60:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'D':
		goto yystate61
	}

yystate61:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate62
	}

yystate62:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate63
	}

yystate63:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate64
	}

yystate64:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate65
	}

yystate65:
	this.next()
	goto yyrule5

yystate66:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'B':
		goto yystate67
	}

yystate67:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'Y':
		goto yystate68
	}

yystate68:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate69
	}

yystate69:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'E':
		goto yystate70
	}

yystate70:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate71
	}

yystate71:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate72
	}

yystate72:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate73
	}

yystate73:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate74
	}

yystate74:
	this.next()
	goto yyrule6

yystate75:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'O':
		goto yystate76
	}

yystate76:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate77
	}

yystate77:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'D':
		goto yystate78
	}

yystate78:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate79
	}

yystate79:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate80
	}

yystate80:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate81
	}

yystate81:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate82
	}

yystate82:
	this.next()
	goto yyrule7

yystate83:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'M':
		goto yystate84
	}

yystate84:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'M':
		goto yystate85
	}

yystate85:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'W':
		goto yystate86
	}

yystate86:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'O':
		goto yystate87
	}

yystate87:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate88
	}

yystate88:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'D':
		goto yystate89
	}

yystate89:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate90
	}

yystate90:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate91
	}

yystate91:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate92
	}

yystate92:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate93
	}

yystate93:
	this.next()
	goto yyrule8

yystate94:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'M':
		goto yystate95
	}

yystate95:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'M':
		goto yystate96
	}

yystate96:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'W':
		goto yystate97
	}

yystate97:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'O':
		goto yystate98
	}

yystate98:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate99
	}

yystate99:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'D':
		goto yystate100
	}

yystate100:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate101
	}

yystate101:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate102
	}

yystate102:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate103
	}

yystate103:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate104
	}

yystate104:
	this.next()
	goto yyrule9

yystate105:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'M':
		goto yystate106
	}

yystate106:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'M':
		goto yystate107
	}

yystate107:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'W':
		goto yystate108
	}

yystate108:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'O':
		goto yystate109
	}

yystate109:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate110
	}

yystate110:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'D':
		goto yystate111
	}

yystate111:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == ' ':
		goto yystate112
	}

yystate112:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'P':
		goto yystate113
	}

yystate113:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'T':
		goto yystate114
	}

yystate114:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'R':
		goto yystate115
	}

yystate115:
	this.next()
	goto yyrule10

yystate116:
	this.next()
	goto yyrule17

yystate117:
	this.next()
	goto yyrule18

yystate118:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'h':
		goto yystate120
	case this.current == 'l':
		goto yystate121
	case this.current == 'x':
		goto yystate122
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'g' || this.current >= 'i' && this.current <= 'k' || this.current >= 'm' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate119:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate120:
	this.next()
	switch {
	default:
		goto yyrule129
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate121:
	this.next()
	switch {
	default:
		goto yyrule174
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate122:
	this.next()
	switch {
	default:
		goto yyrule177
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate123:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'h':
		goto yystate124
	case this.current == 'l':
		goto yystate125
	case this.current == 'n':
		goto yystate126
	case this.current == 'p':
		goto yystate132
	case this.current == 'x':
		goto yystate134
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'g' || this.current >= 'i' && this.current <= 'k' || this.current == 'm' || this.current == 'o' || this.current >= 'q' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate124:
	this.next()
	switch {
	default:
		goto yyrule101
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate125:
	this.next()
	switch {
	default:
		goto yyrule100
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate126:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'd':
		goto yystate127
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'c' || this.current >= 'e' && this.current <= 'z':
		goto yystate119
	}

yystate127:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == '0':
		goto yystate128
	case this.current == '1':
		goto yystate129
	case this.current == '2':
		goto yystate130
	case this.current == '3':
		goto yystate131
	case this.current >= '4' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate128:
	this.next()
	switch {
	default:
		goto yyrule166
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate129:
	this.next()
	switch {
	default:
		goto yyrule167
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate130:
	this.next()
	switch {
	default:
		goto yyrule168
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate131:
	this.next()
	switch {
	default:
		goto yyrule169
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate132:
	this.next()
	switch {
	default:
		goto yyrule176
	case this.current == 'l':
		goto yystate133
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'k' || this.current >= 'm' && this.current <= 'z':
		goto yystate119
	}

yystate133:
	this.next()
	switch {
	default:
		goto yyrule61
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate134:
	this.next()
	switch {
	default:
		goto yyrule112
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate135:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'h':
		goto yystate136
	case this.current == 'l':
		goto yystate137
	case this.current == 's':
		goto yystate138
	case this.current == 'x':
		goto yystate139
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'g' || this.current >= 'i' && this.current <= 'k' || this.current >= 'm' && this.current <= 'r' || this.current >= 't' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate136:
	this.next()
	switch {
	default:
		goto yyrule124
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate137:
	this.next()
	switch {
	default:
		goto yyrule125
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate138:
	this.next()
	switch {
	default:
		goto yyrule127
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate139:
	this.next()
	switch {
	default:
		goto yyrule126
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate140:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'h':
		goto yystate141
	case this.current == 'i':
		goto yystate142
	case this.current == 'l':
		goto yystate144
	case this.current == 's':
		goto yystate145
	case this.current == 'x':
		goto yystate146
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'g' || this.current == 'j' || this.current == 'k' || this.current >= 'm' && this.current <= 'r' || this.current >= 't' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate141:
	this.next()
	switch {
	default:
		goto yyrule179
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate142:
	this.next()
	switch {
	default:
		goto yyrule165
	case this.current == 'l':
		goto yystate143
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'k' || this.current >= 'm' && this.current <= 'z':
		goto yystate119
	}

yystate143:
	this.next()
	switch {
	default:
		goto yyrule58
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate144:
	this.next()
	switch {
	default:
		goto yyrule114
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate145:
	this.next()
	switch {
	default:
		goto yyrule33
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate146:
	this.next()
	switch {
	default:
		goto yyrule54
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate147:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'a':
		goto yystate148
	case this.current == 'b':
		goto yystate150
	case this.current == 'c':
		goto yystate153
	case this.current == 'd':
		goto yystate155
	case this.current == 'f':
		goto yystate158
	case this.current == 's':
		goto yystate163
	case this.current >= '0' && this.current <= '9' || this.current == 'e' || this.current >= 'g' && this.current <= 'r' || this.current >= 't' && this.current <= 'z':
		goto yystate119
	}

yystate148:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'x':
		goto yystate149
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate149:
	this.next()
	switch {
	default:
		goto yyrule203
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate150:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'p':
		goto yystate151
	case this.current == 'x':
		goto yystate152
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'o' || this.current >= 'q' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate151:
	this.next()
	switch {
	default:
		goto yyrule86
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate152:
	this.next()
	switch {
	default:
		goto yyrule122
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate153:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'x':
		goto yystate154
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate154:
	this.next()
	switch {
	default:
		goto yyrule113
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate155:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'i':
		goto yystate156
	case this.current == 'x':
		goto yystate157
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'h' || this.current >= 'j' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate156:
	this.next()
	switch {
	default:
		goto yyrule27
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate157:
	this.next()
	switch {
	default:
		goto yyrule28
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate158:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'l':
		goto yystate159
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'k' || this.current >= 'm' && this.current <= 'z':
		goto yystate119
	}

yystate159:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'a':
		goto yystate160
	case this.current >= '0' && this.current <= '9' || this.current >= 'b' && this.current <= 'z':
		goto yystate119
	}

yystate160:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'g':
		goto yystate161
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'f' || this.current >= 'h' && this.current <= 'z':
		goto yystate119
	}

yystate161:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 's':
		goto yystate162
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'r' || this.current >= 't' && this.current <= 'z':
		goto yystate119
	}

yystate162:
	this.next()
	switch {
	default:
		goto yyrule210
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate163:
	this.next()
	switch {
	default:
		goto yyrule190
	case this.current == 'i':
		goto yystate164
	case this.current == 'p':
		goto yystate165
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'h' || this.current >= 'j' && this.current <= 'o' || this.current >= 'q' && this.current <= 'z':
		goto yystate119
	}

yystate164:
	this.next()
	switch {
	default:
		goto yyrule99
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate165:
	this.next()
	switch {
	default:
		goto yyrule97
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate166:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 's':
		goto yystate167
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'r' || this.current >= 't' && this.current <= 'z':
		goto yystate119
	}

yystate167:
	this.next()
	switch {
	default:
		goto yyrule192
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate168:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 's':
		goto yystate169
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'r' || this.current >= 't' && this.current <= 'z':
		goto yystate119
	}

yystate169:
	this.next()
	switch {
	default:
		goto yyrule25
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate170:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate171:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'o':
		goto yystate172
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'n' || this.current >= 'p' && this.current <= 'z':
		goto yystate119
	}

yystate172:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'c':
		goto yystate173
	case this.current >= '0' && this.current <= '9' || this.current == 'a' || this.current == 'b' || this.current >= 'd' && this.current <= 'z':
		goto yystate119
	}

yystate173:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'k':
		goto yystate174
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'j' || this.current >= 'l' && this.current <= 'z':
		goto yystate119
	}

yystate174:
	this.next()
	switch {
	default:
		goto yyrule216
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate175:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'm':
		goto yystate176
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'l' || this.current >= 'n' && this.current <= 'z':
		goto yystate119
	}

yystate176:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == '0':
		goto yystate177
	case this.current == '1':
		goto yystate178
	case this.current == '2':
		goto yystate179
	case this.current == '3':
		goto yystate180
	case this.current == '4':
		goto yystate181
	case this.current == '5':
		goto yystate182
	case this.current == '6':
		goto yystate183
	case this.current == '7':
		goto yystate184
	case this.current == '8' || this.current == '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate177:
	this.next()
	switch {
	default:
		goto yyrule81
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate178:
	this.next()
	switch {
	default:
		goto yyrule80
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate179:
	this.next()
	switch {
	default:
		goto yyrule83
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate180:
	this.next()
	switch {
	default:
		goto yyrule82
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate181:
	this.next()
	switch {
	default:
		goto yyrule77
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate182:
	this.next()
	switch {
	default:
		goto yyrule76
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate183:
	this.next()
	switch {
	default:
		goto yyrule79
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate184:
	this.next()
	switch {
	default:
		goto yyrule78
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate185:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == '0' || this.current >= '2' && this.current <= '7' || this.current >= 'f' && this.current <= 'r' || this.current >= 't' && this.current <= 'z':
		goto yystate119
	case this.current == '1':
		goto yystate186
	case this.current == '8':
		goto yystate211
	case this.current == '9':
		goto yystate215
	case this.current == 'a':
		goto yystate219
	case this.current == 'b':
		goto yystate221
	case this.current == 'c':
		goto yystate224
	case this.current == 'd':
		goto yystate226
	case this.current == 'e':
		goto yystate229
	case this.current == 's':
		goto yystate236
	}

yystate186:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == '0':
		goto yystate187
	case this.current == '1':
		goto yystate191
	case this.current == '2':
		goto yystate195
	case this.current == '3':
		goto yystate199
	case this.current == '4':
		goto yystate203
	case this.current == '5':
		goto yystate207
	case this.current >= '6' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate187:
	this.next()
	switch {
	default:
		goto yyrule43
	case this.current == 'b':
		goto yystate188
	case this.current == 'd':
		goto yystate189
	case this.current == 'w':
		goto yystate190
	case this.current >= '0' && this.current <= '9' || this.current == 'a' || this.current == 'c' || this.current >= 'e' && this.current <= 'v' || this.current >= 'x' && this.current <= 'z':
		goto yystate119
	}

yystate188:
	this.next()
	switch {
	default:
		goto yyrule59
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate189:
	this.next()
	switch {
	default:
		goto yyrule62
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate190:
	this.next()
	switch {
	default:
		goto yyrule74
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate191:
	this.next()
	switch {
	default:
		goto yyrule44
	case this.current == 'b':
		goto yystate192
	case this.current == 'd':
		goto yystate193
	case this.current == 'w':
		goto yystate194
	case this.current >= '0' && this.current <= '9' || this.current == 'a' || this.current == 'c' || this.current >= 'e' && this.current <= 'v' || this.current >= 'x' && this.current <= 'z':
		goto yystate119
	}

yystate192:
	this.next()
	switch {
	default:
		goto yyrule184
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate193:
	this.next()
	switch {
	default:
		goto yyrule186
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate194:
	this.next()
	switch {
	default:
		goto yyrule191
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate195:
	this.next()
	switch {
	default:
		goto yyrule41
	case this.current == 'b':
		goto yystate196
	case this.current == 'd':
		goto yystate197
	case this.current == 'w':
		goto yystate198
	case this.current >= '0' && this.current <= '9' || this.current == 'a' || this.current == 'c' || this.current >= 'e' && this.current <= 'v' || this.current >= 'x' && this.current <= 'z':
		goto yystate119
	}

yystate196:
	this.next()
	switch {
	default:
		goto yyrule119
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate197:
	this.next()
	switch {
	default:
		goto yyrule120
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate198:
	this.next()
	switch {
	default:
		goto yyrule115
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate199:
	this.next()
	switch {
	default:
		goto yyrule42
	case this.current == 'b':
		goto yystate200
	case this.current == 'd':
		goto yystate201
	case this.current == 'w':
		goto yystate202
	case this.current >= '0' && this.current <= '9' || this.current == 'a' || this.current == 'c' || this.current >= 'e' && this.current <= 'v' || this.current >= 'x' && this.current <= 'z':
		goto yystate119
	}

yystate200:
	this.next()
	switch {
	default:
		goto yyrule35
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate201:
	this.next()
	switch {
	default:
		goto yyrule34
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate202:
	this.next()
	switch {
	default:
		goto yyrule29
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate203:
	this.next()
	switch {
	default:
		goto yyrule39
	case this.current == 'b':
		goto yystate204
	case this.current == 'd':
		goto yystate205
	case this.current == 'w':
		goto yystate206
	case this.current >= '0' && this.current <= '9' || this.current == 'a' || this.current == 'c' || this.current >= 'e' && this.current <= 'v' || this.current >= 'x' && this.current <= 'z':
		goto yystate119
	}

yystate204:
	this.next()
	switch {
	default:
		goto yyrule156
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate205:
	this.next()
	switch {
	default:
		goto yyrule154
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate206:
	this.next()
	switch {
	default:
		goto yyrule162
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate207:
	this.next()
	switch {
	default:
		goto yyrule40
	case this.current == 'b':
		goto yystate208
	case this.current == 'd':
		goto yystate209
	case this.current == 'w':
		goto yystate210
	case this.current >= '0' && this.current <= '9' || this.current == 'a' || this.current == 'c' || this.current >= 'e' && this.current <= 'v' || this.current >= 'x' && this.current <= 'z':
		goto yystate119
	}

yystate208:
	this.next()
	switch {
	default:
		goto yyrule96
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate209:
	this.next()
	switch {
	default:
		goto yyrule95
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate210:
	this.next()
	switch {
	default:
		goto yyrule98
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate211:
	this.next()
	switch {
	default:
		goto yyrule171
	case this.current == 'b':
		goto yystate212
	case this.current == 'd':
		goto yystate213
	case this.current == 'w':
		goto yystate214
	case this.current >= '0' && this.current <= '9' || this.current == 'a' || this.current == 'c' || this.current >= 'e' && this.current <= 'v' || this.current >= 'x' && this.current <= 'z':
		goto yystate119
	}

yystate212:
	this.next()
	switch {
	default:
		goto yyrule31
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate213:
	this.next()
	switch {
	default:
		goto yyrule32
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate214:
	this.next()
	switch {
	default:
		goto yyrule36
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate215:
	this.next()
	switch {
	default:
		goto yyrule118
	case this.current == 'b':
		goto yystate216
	case this.current == 'd':
		goto yystate217
	case this.current == 'w':
		goto yystate218
	case this.current >= '0' && this.current <= '9' || this.current == 'a' || this.current == 'c' || this.current >= 'e' && this.current <= 'v' || this.current >= 'x' && this.current <= 'z':
		goto yystate119
	}

yystate216:
	this.next()
	switch {
	default:
		goto yyrule117
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate217:
	this.next()
	switch {
	default:
		goto yyrule116
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate218:
	this.next()
	switch {
	default:
		goto yyrule121
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate219:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'x':
		goto yystate220
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate220:
	this.next()
	switch {
	default:
		goto yyrule178
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate221:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'p':
		goto yystate222
	case this.current == 'x':
		goto yystate223
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'o' || this.current >= 'q' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate222:
	this.next()
	switch {
	default:
		goto yyrule161
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate223:
	this.next()
	switch {
	default:
		goto yyrule60
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate224:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'x':
		goto yystate225
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate225:
	this.next()
	switch {
	default:
		goto yyrule128
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate226:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'i':
		goto yystate227
	case this.current == 'x':
		goto yystate228
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'h' || this.current >= 'j' && this.current <= 'w' || this.current == 'y' || this.current == 'z':
		goto yystate119
	}

yystate227:
	this.next()
	switch {
	default:
		goto yyrule123
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate228:
	this.next()
	switch {
	default:
		goto yyrule175
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate229:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'p':
		goto yystate230
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'o' || this.current >= 'q' && this.current <= 'z':
		goto yystate119
	}

yystate230:
	this.next()
	switch {
	default:
		goto yyrule211
	case this.current == 'e':
		goto yystate231
	case this.current == 'n':
		goto yystate232
	case this.current == 'z':
		goto yystate235
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'd' || this.current >= 'f' && this.current <= 'm' || this.current >= 'o' && this.current <= 'y':
		goto yystate119
	}

yystate231:
	this.next()
	switch {
	default:
		goto yyrule213
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate232:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'e':
		goto yystate233
	case this.current == 'z':
		goto yystate234
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'd' || this.current >= 'f' && this.current <= 'y':
		goto yystate119
	}

yystate233:
	this.next()
	switch {
	default:
		goto yyrule214
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate234:
	this.next()
	switch {
	default:
		goto yyrule215
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate235:
	this.next()
	switch {
	default:
		goto yyrule212
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate236:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'i':
		goto yystate237
	case this.current == 'p':
		goto yystate238
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'h' || this.current >= 'j' && this.current <= 'o' || this.current >= 'q' && this.current <= 'z':
		goto yystate119
	}

yystate237:
	this.next()
	switch {
	default:
		goto yyrule132
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate238:
	this.next()
	switch {
	default:
		goto yyrule30
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate239:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'i':
		goto yystate240
	case this.current == 'p':
		goto yystate242
	case this.current == 's':
		goto yystate244
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'h' || this.current >= 'j' && this.current <= 'o' || this.current == 'q' || this.current == 'r' || this.current >= 't' && this.current <= 'z':
		goto yystate119
	}

yystate240:
	this.next()
	switch {
	default:
		goto yyrule208
	case this.current == 'l':
		goto yystate241
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'k' || this.current >= 'm' && this.current <= 'z':
		goto yystate119
	}

yystate241:
	this.next()
	switch {
	default:
		goto yyrule73
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate242:
	this.next()
	switch {
	default:
		goto yyrule207
	case this.current == 'l':
		goto yystate243
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'k' || this.current >= 'm' && this.current <= 'z':
		goto yystate119
	}

yystate243:
	this.next()
	switch {
	default:
		goto yyrule164
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate244:
	this.next()
	switch {
	default:
		goto yyrule163
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate245:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'm':
		goto yystate246
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'l' || this.current >= 'n' && this.current <= 'z':
		goto yystate119
	}

yystate246:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'm':
		goto yystate247
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'l' || this.current >= 'n' && this.current <= 'z':
		goto yystate119
	}

yystate247:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == '0':
		goto yystate248
	case this.current == '1':
		goto yystate249
	case this.current == '2':
		goto yystate260
	case this.current == '3':
		goto yystate271
	case this.current == '4':
		goto yystate275
	case this.current == '5':
		goto yystate276
	case this.current == '6':
		goto yystate277
	case this.current == '7':
		goto yystate278
	case this.current == '8':
		goto yystate279
	case this.current == '9':
		goto yystate280
	case this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate248:
	this.next()
	switch {
	default:
		goto yyrule104
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate249:
	this.next()
	switch {
	default:
		goto yyrule105
	case this.current == '0':
		goto yystate250
	case this.current == '1':
		goto yystate251
	case this.current == '2':
		goto yystate252
	case this.current == '3':
		goto yystate253
	case this.current == '4':
		goto yystate254
	case this.current == '5':
		goto yystate255
	case this.current == '6':
		goto yystate256
	case this.current == '7':
		goto yystate257
	case this.current == '8':
		goto yystate258
	case this.current == '9':
		goto yystate259
	case this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate250:
	this.next()
	switch {
	default:
		goto yyrule63
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate251:
	this.next()
	switch {
	default:
		goto yyrule64
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate252:
	this.next()
	switch {
	default:
		goto yyrule65
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate253:
	this.next()
	switch {
	default:
		goto yyrule66
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate254:
	this.next()
	switch {
	default:
		goto yyrule67
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate255:
	this.next()
	switch {
	default:
		goto yyrule68
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate256:
	this.next()
	switch {
	default:
		goto yyrule69
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate257:
	this.next()
	switch {
	default:
		goto yyrule70
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate258:
	this.next()
	switch {
	default:
		goto yyrule71
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate259:
	this.next()
	switch {
	default:
		goto yyrule72
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate260:
	this.next()
	switch {
	default:
		goto yyrule102
	case this.current == '0':
		goto yystate261
	case this.current == '1':
		goto yystate262
	case this.current == '2':
		goto yystate263
	case this.current == '3':
		goto yystate264
	case this.current == '4':
		goto yystate265
	case this.current == '5':
		goto yystate266
	case this.current == '6':
		goto yystate267
	case this.current == '7':
		goto yystate268
	case this.current == '8':
		goto yystate269
	case this.current == '9':
		goto yystate270
	case this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate261:
	this.next()
	switch {
	default:
		goto yyrule134
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate262:
	this.next()
	switch {
	default:
		goto yyrule133
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate263:
	this.next()
	switch {
	default:
		goto yyrule136
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate264:
	this.next()
	switch {
	default:
		goto yyrule135
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate265:
	this.next()
	switch {
	default:
		goto yyrule138
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate266:
	this.next()
	switch {
	default:
		goto yyrule137
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate267:
	this.next()
	switch {
	default:
		goto yyrule140
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate268:
	this.next()
	switch {
	default:
		goto yyrule139
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate269:
	this.next()
	switch {
	default:
		goto yyrule131
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate270:
	this.next()
	switch {
	default:
		goto yyrule130
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate271:
	this.next()
	switch {
	default:
		goto yyrule103
	case this.current == '0':
		goto yystate272
	case this.current == '1':
		goto yystate273
	case this.current == '2':
		goto yystate274
	case this.current >= '3' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate272:
	this.next()
	switch {
	default:
		goto yyrule172
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate273:
	this.next()
	switch {
	default:
		goto yyrule173
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate274:
	this.next()
	switch {
	default:
		goto yyrule170
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate275:
	this.next()
	switch {
	default:
		goto yyrule108
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate276:
	this.next()
	switch {
	default:
		goto yyrule109
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate277:
	this.next()
	switch {
	default:
		goto yyrule106
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate278:
	this.next()
	switch {
	default:
		goto yyrule107
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate279:
	this.next()
	switch {
	default:
		goto yyrule110
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate280:
	this.next()
	switch {
	default:
		goto yyrule111
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate281:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'm':
		goto yystate282
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'l' || this.current >= 'n' && this.current <= 'z':
		goto yystate119
	}

yystate282:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'm':
		goto yystate283
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'l' || this.current >= 'n' && this.current <= 'z':
		goto yystate119
	}

yystate283:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == '0':
		goto yystate284
	case this.current == '1':
		goto yystate285
	case this.current == '2':
		goto yystate296
	case this.current == '3':
		goto yystate307
	case this.current == '4':
		goto yystate311
	case this.current == '5':
		goto yystate312
	case this.current == '6':
		goto yystate313
	case this.current == '7':
		goto yystate314
	case this.current == '8':
		goto yystate315
	case this.current == '9':
		goto yystate316
	case this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate284:
	this.next()
	switch {
	default:
		goto yyrule46
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate285:
	this.next()
	switch {
	default:
		goto yyrule45
	case this.current == '0':
		goto yystate286
	case this.current == '1':
		goto yystate287
	case this.current == '2':
		goto yystate288
	case this.current == '3':
		goto yystate289
	case this.current == '4':
		goto yystate290
	case this.current == '5':
		goto yystate291
	case this.current == '6':
		goto yystate292
	case this.current == '7':
		goto yystate293
	case this.current == '8':
		goto yystate294
	case this.current == '9':
		goto yystate295
	case this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate286:
	this.next()
	switch {
	default:
		goto yyrule194
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate287:
	this.next()
	switch {
	default:
		goto yyrule193
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate288:
	this.next()
	switch {
	default:
		goto yyrule196
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate289:
	this.next()
	switch {
	default:
		goto yyrule195
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate290:
	this.next()
	switch {
	default:
		goto yyrule198
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate291:
	this.next()
	switch {
	default:
		goto yyrule197
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate292:
	this.next()
	switch {
	default:
		goto yyrule200
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate293:
	this.next()
	switch {
	default:
		goto yyrule199
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate294:
	this.next()
	switch {
	default:
		goto yyrule202
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate295:
	this.next()
	switch {
	default:
		goto yyrule201
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate296:
	this.next()
	switch {
	default:
		goto yyrule48
	case this.current == '0':
		goto yystate297
	case this.current == '1':
		goto yystate298
	case this.current == '2':
		goto yystate299
	case this.current == '3':
		goto yystate300
	case this.current == '4':
		goto yystate301
	case this.current == '5':
		goto yystate302
	case this.current == '6':
		goto yystate303
	case this.current == '7':
		goto yystate304
	case this.current == '8':
		goto yystate305
	case this.current == '9':
		goto yystate306
	case this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate297:
	this.next()
	switch {
	default:
		goto yyrule87
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate298:
	this.next()
	switch {
	default:
		goto yyrule88
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate299:
	this.next()
	switch {
	default:
		goto yyrule89
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate300:
	this.next()
	switch {
	default:
		goto yyrule90
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate301:
	this.next()
	switch {
	default:
		goto yyrule91
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate302:
	this.next()
	switch {
	default:
		goto yyrule92
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate303:
	this.next()
	switch {
	default:
		goto yyrule93
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate304:
	this.next()
	switch {
	default:
		goto yyrule94
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate305:
	this.next()
	switch {
	default:
		goto yyrule84
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate306:
	this.next()
	switch {
	default:
		goto yyrule85
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate307:
	this.next()
	switch {
	default:
		goto yyrule47
	case this.current == '0':
		goto yystate308
	case this.current == '1':
		goto yystate309
	case this.current == '2':
		goto yystate310
	case this.current >= '3' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate308:
	this.next()
	switch {
	default:
		goto yyrule57
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate309:
	this.next()
	switch {
	default:
		goto yyrule56
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate310:
	this.next()
	switch {
	default:
		goto yyrule55
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate311:
	this.next()
	switch {
	default:
		goto yyrule50
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate312:
	this.next()
	switch {
	default:
		goto yyrule49
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate313:
	this.next()
	switch {
	default:
		goto yyrule52
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate314:
	this.next()
	switch {
	default:
		goto yyrule51
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate315:
	this.next()
	switch {
	default:
		goto yyrule38
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate316:
	this.next()
	switch {
	default:
		goto yyrule37
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate317:
	this.next()
	switch {
	default:
		goto yyabort
	case this.current == 'm':
		goto yystate318
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'l' || this.current >= 'n' && this.current <= 'z':
		goto yystate119
	}

yystate318:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == 'm':
		goto yystate319
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'l' || this.current >= 'n' && this.current <= 'z':
		goto yystate119
	}

yystate319:
	this.next()
	switch {
	default:
		goto yyrule220
	case this.current == '0':
		goto yystate320
	case this.current == '1':
		goto yystate321
	case this.current == '2':
		goto yystate332
	case this.current == '3':
		goto yystate343
	case this.current == '4':
		goto yystate347
	case this.current == '5':
		goto yystate348
	case this.current == '6':
		goto yystate349
	case this.current == '7':
		goto yystate350
	case this.current == '8':
		goto yystate351
	case this.current == '9':
		goto yystate352
	case this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate320:
	this.next()
	switch {
	default:
		goto yyrule143
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate321:
	this.next()
	switch {
	default:
		goto yyrule144
	case this.current == '0':
		goto yystate322
	case this.current == '1':
		goto yystate323
	case this.current == '2':
		goto yystate324
	case this.current == '3':
		goto yystate325
	case this.current == '4':
		goto yystate326
	case this.current == '5':
		goto yystate327
	case this.current == '6':
		goto yystate328
	case this.current == '7':
		goto yystate329
	case this.current == '8':
		goto yystate330
	case this.current == '9':
		goto yystate331
	case this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate322:
	this.next()
	switch {
	default:
		goto yyrule153
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate323:
	this.next()
	switch {
	default:
		goto yyrule53
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate324:
	this.next()
	switch {
	default:
		goto yyrule151
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate325:
	this.next()
	switch {
	default:
		goto yyrule152
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate326:
	this.next()
	switch {
	default:
		goto yyrule157
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate327:
	this.next()
	switch {
	default:
		goto yyrule158
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate328:
	this.next()
	switch {
	default:
		goto yyrule155
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate329:
	this.next()
	switch {
	default:
		goto yyrule75
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate330:
	this.next()
	switch {
	default:
		goto yyrule159
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate331:
	this.next()
	switch {
	default:
		goto yyrule160
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate332:
	this.next()
	switch {
	default:
		goto yyrule145
	case this.current == '0':
		goto yystate333
	case this.current == '1':
		goto yystate334
	case this.current == '2':
		goto yystate335
	case this.current == '3':
		goto yystate336
	case this.current == '4':
		goto yystate337
	case this.current == '5':
		goto yystate338
	case this.current == '6':
		goto yystate339
	case this.current == '7':
		goto yystate340
	case this.current == '8':
		goto yystate341
	case this.current == '9':
		goto yystate342
	case this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate333:
	this.next()
	switch {
	default:
		goto yyrule189
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate334:
	this.next()
	switch {
	default:
		goto yyrule188
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate335:
	this.next()
	switch {
	default:
		goto yyrule187
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate336:
	this.next()
	switch {
	default:
		goto yyrule26
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate337:
	this.next()
	switch {
	default:
		goto yyrule185
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate338:
	this.next()
	switch {
	default:
		goto yyrule209
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate339:
	this.next()
	switch {
	default:
		goto yyrule183
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate340:
	this.next()
	switch {
	default:
		goto yyrule182
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate341:
	this.next()
	switch {
	default:
		goto yyrule181
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate342:
	this.next()
	switch {
	default:
		goto yyrule180
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate343:
	this.next()
	switch {
	default:
		goto yyrule146
	case this.current == '0':
		goto yystate344
	case this.current == '1':
		goto yystate345
	case this.current == '2':
		goto yystate346
	case this.current >= '3' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate344:
	this.next()
	switch {
	default:
		goto yyrule204
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate345:
	this.next()
	switch {
	default:
		goto yyrule205
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate346:
	this.next()
	switch {
	default:
		goto yyrule206
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate347:
	this.next()
	switch {
	default:
		goto yyrule147
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate348:
	this.next()
	switch {
	default:
		goto yyrule148
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate349:
	this.next()
	switch {
	default:
		goto yyrule149
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate350:
	this.next()
	switch {
	default:
		goto yyrule150
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate351:
	this.next()
	switch {
	default:
		goto yyrule141
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yystate352:
	this.next()
	switch {
	default:
		goto yyrule142
	case this.current >= '0' && this.current <= '9' || this.current >= 'a' && this.current <= 'z':
		goto yystate119
	}

yyrule1: // (BYTE\ PTR)
	{
		{
			lval.u64 = BYTE_PTR
			return BYTE_PTR
		}
		goto yystate0
	}
yyrule2: // (DWORD\ PTR)
	{
		{
			lval.u64 = DWORD_PTR
			return DWORD_PTR
		}
		goto yystate0
	}
yyrule3: // (FWORD\ PTR)
	{
		{
			lval.u64 = FWORD_PTR
			return FWORD_PTR
		}
		goto yystate0
	}
yyrule4: // (OWORD\ PTR)
	{
		{
			lval.u64 = OWORD_PTR
			return OWORD_PTR
		}
		goto yystate0
	}
yyrule5: // (QWORD\ PTR)
	{
		{
			lval.u64 = QWORD_PTR
			return QWORD_PTR
		}
		goto yystate0
	}
yyrule6: // (TBYTE\ PTR)
	{
		{
			lval.u64 = TBYTE_PTR
			return TBYTE_PTR
		}
		goto yystate0
	}
yyrule7: // (WORD\ PTR)
	{
		{
			lval.u64 = WORD_PTR
			return WORD_PTR
		}
		goto yystate0
	}
yyrule8: // (XMMWORD\ PTR)
	{
		{
			lval.u64 = XMMWORD_PTR
			return XMMWORD_PTR
		}
		goto yystate0
	}
yyrule9: // (YMMWORD\ PTR)
	{
		{
			lval.u64 = YMMWORD_PTR
			return YMMWORD_PTR
		}
		goto yystate0
	}
yyrule10: // (ZMMWORD\ PTR)
	{
		{
			lval.u64 = ZMMWORD_PTR
			return ZMMWORD_PTR
		}
		goto yystate0
	}
yyrule11: // 0[xX][0-9a-f]+
	{
		{
			/* HEXNUMBER */
			var err error
			if lval.u64, err = strconv.ParseUint(string(this.buf), 0, 64); err != nil {
				panic(err)
			}
			return HEXNUMBER
		}
		goto yystate0
	}
yyrule12: // \n
	{
		return '\n'
	}
yyrule13: // :
	{
		return ':'
	}
yyrule14: // \+
	{
		return '+'
	}
yyrule15: // -
	{
		return '-'
	}
yyrule16: // \*
	{
		return '*'
	}
yyrule17: // \[
	{
		return '['
	}
yyrule18: // \]
	{
		return ']'
	}
yyrule19: // ,
	{
		return ','
	}
yyrule20: // 1
	{
		return '1'
	}
yyrule21: // 2
	{
		return '2'
	}
yyrule22: // 4
	{
		return '4'
	}
yyrule23: // 8
	{
		return '8'
	}
yyrule24: // \0
	{
		return 0
	}
yyrule25: // gs
	{
		{
			lval.str = "gs"
			return TOKEN_REG_GS
		}
		goto yystate0
	}
yyrule26: // zmm23
	{
		{
			lval.str = "zmm23"
			return TOKEN_REG_ZMM23
		}
		goto yystate0
	}
yyrule27: // edi
	{
		{
			lval.str = "edi"
			return TOKEN_REG_EDI
		}
		goto yystate0
	}
yyrule28: // edx
	{
		{
			lval.str = "edx"
			return TOKEN_REG_EDX
		}
		goto yystate0
	}
yyrule29: // r13w
	{
		{
			lval.str = "r13w"
			return TOKEN_REG_R13W
		}
		goto yystate0
	}
yyrule30: // rsp
	{
		{
			lval.str = "rsp"
			return TOKEN_REG_RSP
		}
		goto yystate0
	}
yyrule31: // r8b
	{
		{
			lval.str = "r8b"
			return TOKEN_REG_R8B
		}
		goto yystate0
	}
yyrule32: // r8d
	{
		{
			lval.str = "r8d"
			return TOKEN_REG_R8D
		}
		goto yystate0
	}
yyrule33: // ds
	{
		{
			lval.str = "ds"
			return TOKEN_REG_DS
		}
		goto yystate0
	}
yyrule34: // r13d
	{
		{
			lval.str = "r13d"
			return TOKEN_REG_R13D
		}
		goto yystate0
	}
yyrule35: // r13b
	{
		{
			lval.str = "r13b"
			return TOKEN_REG_R13B
		}
		goto yystate0
	}
yyrule36: // r8w
	{
		{
			lval.str = "r8w"
			return TOKEN_REG_R8W
		}
		goto yystate0
	}
yyrule37: // ymm9
	{
		{
			lval.str = "ymm9"
			return TOKEN_REG_YMM9
		}
		goto yystate0
	}
yyrule38: // ymm8
	{
		{
			lval.str = "ymm8"
			return TOKEN_REG_YMM8
		}
		goto yystate0
	}
yyrule39: // r14
	{
		{
			lval.str = "r14"
			return TOKEN_REG_R14
		}
		goto yystate0
	}
yyrule40: // r15
	{
		{
			lval.str = "r15"
			return TOKEN_REG_R15
		}
		goto yystate0
	}
yyrule41: // r12
	{
		{
			lval.str = "r12"
			return TOKEN_REG_R12
		}
		goto yystate0
	}
yyrule42: // r13
	{
		{
			lval.str = "r13"
			return TOKEN_REG_R13
		}
		goto yystate0
	}
yyrule43: // r10
	{
		{
			lval.str = "r10"
			return TOKEN_REG_R10
		}
		goto yystate0
	}
yyrule44: // r11
	{
		{
			lval.str = "r11"
			return TOKEN_REG_R11
		}
		goto yystate0
	}
yyrule45: // ymm1
	{
		{
			lval.str = "ymm1"
			return TOKEN_REG_YMM1
		}
		goto yystate0
	}
yyrule46: // ymm0
	{
		{
			lval.str = "ymm0"
			return TOKEN_REG_YMM0
		}
		goto yystate0
	}
yyrule47: // ymm3
	{
		{
			lval.str = "ymm3"
			return TOKEN_REG_YMM3
		}
		goto yystate0
	}
yyrule48: // ymm2
	{
		{
			lval.str = "ymm2"
			return TOKEN_REG_YMM2
		}
		goto yystate0
	}
yyrule49: // ymm5
	{
		{
			lval.str = "ymm5"
			return TOKEN_REG_YMM5
		}
		goto yystate0
	}
yyrule50: // ymm4
	{
		{
			lval.str = "ymm4"
			return TOKEN_REG_YMM4
		}
		goto yystate0
	}
yyrule51: // ymm7
	{
		{
			lval.str = "ymm7"
			return TOKEN_REG_YMM7
		}
		goto yystate0
	}
yyrule52: // ymm6
	{
		{
			lval.str = "ymm6"
			return TOKEN_REG_YMM6
		}
		goto yystate0
	}
yyrule53: // zmm11
	{
		{
			lval.str = "zmm11"
			return TOKEN_REG_ZMM11
		}
		goto yystate0
	}
yyrule54: // dx
	{
		{
			lval.str = "dx"
			return TOKEN_REG_DX
		}
		goto yystate0
	}
yyrule55: // ymm32
	{
		{
			lval.str = "ymm32"
			return TOKEN_REG_YMM32
		}
		goto yystate0
	}
yyrule56: // ymm31
	{
		{
			lval.str = "ymm31"
			return TOKEN_REG_YMM31
		}
		goto yystate0
	}
yyrule57: // ymm30
	{
		{
			lval.str = "ymm30"
			return TOKEN_REG_YMM30
		}
		goto yystate0
	}
yyrule58: // dil
	{
		{
			lval.str = "dil"
			return TOKEN_REG_DIL
		}
		goto yystate0
	}
yyrule59: // r10b
	{
		{
			lval.str = "r10b"
			return TOKEN_REG_R10B
		}
		goto yystate0
	}
yyrule60: // rbx
	{
		{
			lval.str = "rbx"
			return TOKEN_REG_RBX
		}
		goto yystate0
	}
yyrule61: // bpl
	{
		{
			lval.str = "bpl"
			return TOKEN_REG_BPL
		}
		goto yystate0
	}
yyrule62: // r10d
	{
		{
			lval.str = "r10d"
			return TOKEN_REG_R10D
		}
		goto yystate0
	}
yyrule63: // xmm10
	{
		{
			lval.str = "xmm10"
			return TOKEN_REG_XMM10
		}
		goto yystate0
	}
yyrule64: // xmm11
	{
		{
			lval.str = "xmm11"
			return TOKEN_REG_XMM11
		}
		goto yystate0
	}
yyrule65: // xmm12
	{
		{
			lval.str = "xmm12"
			return TOKEN_REG_XMM12
		}
		goto yystate0
	}
yyrule66: // xmm13
	{
		{
			lval.str = "xmm13"
			return TOKEN_REG_XMM13
		}
		goto yystate0
	}
yyrule67: // xmm14
	{
		{
			lval.str = "xmm14"
			return TOKEN_REG_XMM14
		}
		goto yystate0
	}
yyrule68: // xmm15
	{
		{
			lval.str = "xmm15"
			return TOKEN_REG_XMM15
		}
		goto yystate0
	}
yyrule69: // xmm16
	{
		{
			lval.str = "xmm16"
			return TOKEN_REG_XMM16
		}
		goto yystate0
	}
yyrule70: // xmm17
	{
		{
			lval.str = "xmm17"
			return TOKEN_REG_XMM17
		}
		goto yystate0
	}
yyrule71: // xmm18
	{
		{
			lval.str = "xmm18"
			return TOKEN_REG_XMM18
		}
		goto yystate0
	}
yyrule72: // xmm19
	{
		{
			lval.str = "xmm19"
			return TOKEN_REG_XMM19
		}
		goto yystate0
	}
yyrule73: // sil
	{
		{
			lval.str = "sil"
			return TOKEN_REG_SIL
		}
		goto yystate0
	}
yyrule74: // r10w
	{
		{
			lval.str = "r10w"
			return TOKEN_REG_R10W
		}
		goto yystate0
	}
yyrule75: // zmm17
	{
		{
			lval.str = "zmm17"
			return TOKEN_REG_ZMM17
		}
		goto yystate0
	}
yyrule76: // mm5
	{
		{
			lval.str = "mm5"
			return TOKEN_REG_MM5
		}
		goto yystate0
	}
yyrule77: // mm4
	{
		{
			lval.str = "mm4"
			return TOKEN_REG_MM4
		}
		goto yystate0
	}
yyrule78: // mm7
	{
		{
			lval.str = "mm7"
			return TOKEN_REG_MM7
		}
		goto yystate0
	}
yyrule79: // mm6
	{
		{
			lval.str = "mm6"
			return TOKEN_REG_MM6
		}
		goto yystate0
	}
yyrule80: // mm1
	{
		{
			lval.str = "mm1"
			return TOKEN_REG_MM1
		}
		goto yystate0
	}
yyrule81: // mm0
	{
		{
			lval.str = "mm0"
			return TOKEN_REG_MM0
		}
		goto yystate0
	}
yyrule82: // mm3
	{
		{
			lval.str = "mm3"
			return TOKEN_REG_MM3
		}
		goto yystate0
	}
yyrule83: // mm2
	{
		{
			lval.str = "mm2"
			return TOKEN_REG_MM2
		}
		goto yystate0
	}
yyrule84: // ymm28
	{
		{
			lval.str = "ymm28"
			return TOKEN_REG_YMM28
		}
		goto yystate0
	}
yyrule85: // ymm29
	{
		{
			lval.str = "ymm29"
			return TOKEN_REG_YMM29
		}
		goto yystate0
	}
yyrule86: // ebp
	{
		{
			lval.str = "ebp"
			return TOKEN_REG_EBP
		}
		goto yystate0
	}
yyrule87: // ymm20
	{
		{
			lval.str = "ymm20"
			return TOKEN_REG_YMM20
		}
		goto yystate0
	}
yyrule88: // ymm21
	{
		{
			lval.str = "ymm21"
			return TOKEN_REG_YMM21
		}
		goto yystate0
	}
yyrule89: // ymm22
	{
		{
			lval.str = "ymm22"
			return TOKEN_REG_YMM22
		}
		goto yystate0
	}
yyrule90: // ymm23
	{
		{
			lval.str = "ymm23"
			return TOKEN_REG_YMM23
		}
		goto yystate0
	}
yyrule91: // ymm24
	{
		{
			lval.str = "ymm24"
			return TOKEN_REG_YMM24
		}
		goto yystate0
	}
yyrule92: // ymm25
	{
		{
			lval.str = "ymm25"
			return TOKEN_REG_YMM25
		}
		goto yystate0
	}
yyrule93: // ymm26
	{
		{
			lval.str = "ymm26"
			return TOKEN_REG_YMM26
		}
		goto yystate0
	}
yyrule94: // ymm27
	{
		{
			lval.str = "ymm27"
			return TOKEN_REG_YMM27
		}
		goto yystate0
	}
yyrule95: // r15d
	{
		{
			lval.str = "r15d"
			return TOKEN_REG_R15D
		}
		goto yystate0
	}
yyrule96: // r15b
	{
		{
			lval.str = "r15b"
			return TOKEN_REG_R15B
		}
		goto yystate0
	}
yyrule97: // esp
	{
		{
			lval.str = "esp"
			return TOKEN_REG_ESP
		}
		goto yystate0
	}
yyrule98: // r15w
	{
		{
			lval.str = "r15w"
			return TOKEN_REG_R15W
		}
		goto yystate0
	}
yyrule99: // esi
	{
		{
			lval.str = "esi"
			return TOKEN_REG_ESI
		}
		goto yystate0
	}
yyrule100: // bl
	{
		{
			lval.str = "bl"
			return TOKEN_REG_BL
		}
		goto yystate0
	}
yyrule101: // bh
	{
		{
			lval.str = "bh"
			return TOKEN_REG_BH
		}
		goto yystate0
	}
yyrule102: // xmm2
	{
		{
			lval.str = "xmm2"
			return TOKEN_REG_XMM2
		}
		goto yystate0
	}
yyrule103: // xmm3
	{
		{
			lval.str = "xmm3"
			return TOKEN_REG_XMM3
		}
		goto yystate0
	}
yyrule104: // xmm0
	{
		{
			lval.str = "xmm0"
			return TOKEN_REG_XMM0
		}
		goto yystate0
	}
yyrule105: // xmm1
	{
		{
			lval.str = "xmm1"
			return TOKEN_REG_XMM1
		}
		goto yystate0
	}
yyrule106: // xmm6
	{
		{
			lval.str = "xmm6"
			return TOKEN_REG_XMM6
		}
		goto yystate0
	}
yyrule107: // xmm7
	{
		{
			lval.str = "xmm7"
			return TOKEN_REG_XMM7
		}
		goto yystate0
	}
yyrule108: // xmm4
	{
		{
			lval.str = "xmm4"
			return TOKEN_REG_XMM4
		}
		goto yystate0
	}
yyrule109: // xmm5
	{
		{
			lval.str = "xmm5"
			return TOKEN_REG_XMM5
		}
		goto yystate0
	}
yyrule110: // xmm8
	{
		{
			lval.str = "xmm8"
			return TOKEN_REG_XMM8
		}
		goto yystate0
	}
yyrule111: // xmm9
	{
		{
			lval.str = "xmm9"
			return TOKEN_REG_XMM9
		}
		goto yystate0
	}
yyrule112: // bx
	{
		{
			lval.str = "bx"
			return TOKEN_REG_BX
		}
		goto yystate0
	}
yyrule113: // ecx
	{
		{
			lval.str = "ecx"
			return TOKEN_REG_ECX
		}
		goto yystate0
	}
yyrule114: // dl
	{
		{
			lval.str = "dl"
			return TOKEN_REG_DL
		}
		goto yystate0
	}
yyrule115: // r12w
	{
		{
			lval.str = "r12w"
			return TOKEN_REG_R12W
		}
		goto yystate0
	}
yyrule116: // r9d
	{
		{
			lval.str = "r9d"
			return TOKEN_REG_R9D
		}
		goto yystate0
	}
yyrule117: // r9b
	{
		{
			lval.str = "r9b"
			return TOKEN_REG_R9B
		}
		goto yystate0
	}
yyrule118: // r9
	{
		{
			lval.str = "r9"
			return TOKEN_REG_R9
		}
		goto yystate0
	}
yyrule119: // r12b
	{
		{
			lval.str = "r12b"
			return TOKEN_REG_R12B
		}
		goto yystate0
	}
yyrule120: // r12d
	{
		{
			lval.str = "r12d"
			return TOKEN_REG_R12D
		}
		goto yystate0
	}
yyrule121: // r9w
	{
		{
			lval.str = "r9w"
			return TOKEN_REG_R9W
		}
		goto yystate0
	}
yyrule122: // ebx
	{
		{
			lval.str = "ebx"
			return TOKEN_REG_EBX
		}
		goto yystate0
	}
yyrule123: // rdi
	{
		{
			lval.str = "rdi"
			return TOKEN_REG_RDI
		}
		goto yystate0
	}
yyrule124: // ch
	{
		{
			lval.str = "ch"
			return TOKEN_REG_CH
		}
		goto yystate0
	}
yyrule125: // cl
	{
		{
			lval.str = "cl"
			return TOKEN_REG_CL
		}
		goto yystate0
	}
yyrule126: // cx
	{
		{
			lval.str = "cx"
			return TOKEN_REG_CX
		}
		goto yystate0
	}
yyrule127: // cs
	{
		{
			lval.str = "cs"
			return TOKEN_REG_CS
		}
		goto yystate0
	}
yyrule128: // rcx
	{
		{
			lval.str = "rcx"
			return TOKEN_REG_RCX
		}
		goto yystate0
	}
yyrule129: // ah
	{
		{
			lval.str = "ah"
			return TOKEN_REG_AH
		}
		goto yystate0
	}
yyrule130: // xmm29
	{
		{
			lval.str = "xmm29"
			return TOKEN_REG_XMM29
		}
		goto yystate0
	}
yyrule131: // xmm28
	{
		{
			lval.str = "xmm28"
			return TOKEN_REG_XMM28
		}
		goto yystate0
	}
yyrule132: // rsi
	{
		{
			lval.str = "rsi"
			return TOKEN_REG_RSI
		}
		goto yystate0
	}
yyrule133: // xmm21
	{
		{
			lval.str = "xmm21"
			return TOKEN_REG_XMM21
		}
		goto yystate0
	}
yyrule134: // xmm20
	{
		{
			lval.str = "xmm20"
			return TOKEN_REG_XMM20
		}
		goto yystate0
	}
yyrule135: // xmm23
	{
		{
			lval.str = "xmm23"
			return TOKEN_REG_XMM23
		}
		goto yystate0
	}
yyrule136: // xmm22
	{
		{
			lval.str = "xmm22"
			return TOKEN_REG_XMM22
		}
		goto yystate0
	}
yyrule137: // xmm25
	{
		{
			lval.str = "xmm25"
			return TOKEN_REG_XMM25
		}
		goto yystate0
	}
yyrule138: // xmm24
	{
		{
			lval.str = "xmm24"
			return TOKEN_REG_XMM24
		}
		goto yystate0
	}
yyrule139: // xmm27
	{
		{
			lval.str = "xmm27"
			return TOKEN_REG_XMM27
		}
		goto yystate0
	}
yyrule140: // xmm26
	{
		{
			lval.str = "xmm26"
			return TOKEN_REG_XMM26
		}
		goto yystate0
	}
yyrule141: // zmm8
	{
		{
			lval.str = "zmm8"
			return TOKEN_REG_ZMM8
		}
		goto yystate0
	}
yyrule142: // zmm9
	{
		{
			lval.str = "zmm9"
			return TOKEN_REG_ZMM9
		}
		goto yystate0
	}
yyrule143: // zmm0
	{
		{
			lval.str = "zmm0"
			return TOKEN_REG_ZMM0
		}
		goto yystate0
	}
yyrule144: // zmm1
	{
		{
			lval.str = "zmm1"
			return TOKEN_REG_ZMM1
		}
		goto yystate0
	}
yyrule145: // zmm2
	{
		{
			lval.str = "zmm2"
			return TOKEN_REG_ZMM2
		}
		goto yystate0
	}
yyrule146: // zmm3
	{
		{
			lval.str = "zmm3"
			return TOKEN_REG_ZMM3
		}
		goto yystate0
	}
yyrule147: // zmm4
	{
		{
			lval.str = "zmm4"
			return TOKEN_REG_ZMM4
		}
		goto yystate0
	}
yyrule148: // zmm5
	{
		{
			lval.str = "zmm5"
			return TOKEN_REG_ZMM5
		}
		goto yystate0
	}
yyrule149: // zmm6
	{
		{
			lval.str = "zmm6"
			return TOKEN_REG_ZMM6
		}
		goto yystate0
	}
yyrule150: // zmm7
	{
		{
			lval.str = "zmm7"
			return TOKEN_REG_ZMM7
		}
		goto yystate0
	}
yyrule151: // zmm12
	{
		{
			lval.str = "zmm12"
			return TOKEN_REG_ZMM12
		}
		goto yystate0
	}
yyrule152: // zmm13
	{
		{
			lval.str = "zmm13"
			return TOKEN_REG_ZMM13
		}
		goto yystate0
	}
yyrule153: // zmm10
	{
		{
			lval.str = "zmm10"
			return TOKEN_REG_ZMM10
		}
		goto yystate0
	}
yyrule154: // r14d
	{
		{
			lval.str = "r14d"
			return TOKEN_REG_R14D
		}
		goto yystate0
	}
yyrule155: // zmm16
	{
		{
			lval.str = "zmm16"
			return TOKEN_REG_ZMM16
		}
		goto yystate0
	}
yyrule156: // r14b
	{
		{
			lval.str = "r14b"
			return TOKEN_REG_R14B
		}
		goto yystate0
	}
yyrule157: // zmm14
	{
		{
			lval.str = "zmm14"
			return TOKEN_REG_ZMM14
		}
		goto yystate0
	}
yyrule158: // zmm15
	{
		{
			lval.str = "zmm15"
			return TOKEN_REG_ZMM15
		}
		goto yystate0
	}
yyrule159: // zmm18
	{
		{
			lval.str = "zmm18"
			return TOKEN_REG_ZMM18
		}
		goto yystate0
	}
yyrule160: // zmm19
	{
		{
			lval.str = "zmm19"
			return TOKEN_REG_ZMM19
		}
		goto yystate0
	}
yyrule161: // rbp
	{
		{
			lval.str = "rbp"
			return TOKEN_REG_RBP
		}
		goto yystate0
	}
yyrule162: // r14w
	{
		{
			lval.str = "r14w"
			return TOKEN_REG_R14W
		}
		goto yystate0
	}
yyrule163: // ss
	{
		{
			lval.str = "ss"
			return TOKEN_REG_SS
		}
		goto yystate0
	}
yyrule164: // spl
	{
		{
			lval.str = "spl"
			return TOKEN_REG_SPL
		}
		goto yystate0
	}
yyrule165: // di
	{
		{
			lval.str = "di"
			return TOKEN_REG_DI
		}
		goto yystate0
	}
yyrule166: // bnd0
	{
		{
			lval.str = "bnd0"
			return TOKEN_REG_BND0
		}
		goto yystate0
	}
yyrule167: // bnd1
	{
		{
			lval.str = "bnd1"
			return TOKEN_REG_BND1
		}
		goto yystate0
	}
yyrule168: // bnd2
	{
		{
			lval.str = "bnd2"
			return TOKEN_REG_BND2
		}
		goto yystate0
	}
yyrule169: // bnd3
	{
		{
			lval.str = "bnd3"
			return TOKEN_REG_BND3
		}
		goto yystate0
	}
yyrule170: // xmm32
	{
		{
			lval.str = "xmm32"
			return TOKEN_REG_XMM32
		}
		goto yystate0
	}
yyrule171: // r8
	{
		{
			lval.str = "r8"
			return TOKEN_REG_R8
		}
		goto yystate0
	}
yyrule172: // xmm30
	{
		{
			lval.str = "xmm30"
			return TOKEN_REG_XMM30
		}
		goto yystate0
	}
yyrule173: // xmm31
	{
		{
			lval.str = "xmm31"
			return TOKEN_REG_XMM31
		}
		goto yystate0
	}
yyrule174: // al
	{
		{
			lval.str = "al"
			return TOKEN_REG_AL
		}
		goto yystate0
	}
yyrule175: // rdx
	{
		{
			lval.str = "rdx"
			return TOKEN_REG_RDX
		}
		goto yystate0
	}
yyrule176: // bp
	{
		{
			lval.str = "bp"
			return TOKEN_REG_BP
		}
		goto yystate0
	}
yyrule177: // ax
	{
		{
			lval.str = "ax"
			return TOKEN_REG_AX
		}
		goto yystate0
	}
yyrule178: // rax
	{
		{
			lval.str = "rax"
			return TOKEN_REG_RAX
		}
		goto yystate0
	}
yyrule179: // dh
	{
		{
			lval.str = "dh"
			return TOKEN_REG_DH
		}
		goto yystate0
	}
yyrule180: // zmm29
	{
		{
			lval.str = "zmm29"
			return TOKEN_REG_ZMM29
		}
		goto yystate0
	}
yyrule181: // zmm28
	{
		{
			lval.str = "zmm28"
			return TOKEN_REG_ZMM28
		}
		goto yystate0
	}
yyrule182: // zmm27
	{
		{
			lval.str = "zmm27"
			return TOKEN_REG_ZMM27
		}
		goto yystate0
	}
yyrule183: // zmm26
	{
		{
			lval.str = "zmm26"
			return TOKEN_REG_ZMM26
		}
		goto yystate0
	}
yyrule184: // r11b
	{
		{
			lval.str = "r11b"
			return TOKEN_REG_R11B
		}
		goto yystate0
	}
yyrule185: // zmm24
	{
		{
			lval.str = "zmm24"
			return TOKEN_REG_ZMM24
		}
		goto yystate0
	}
yyrule186: // r11d
	{
		{
			lval.str = "r11d"
			return TOKEN_REG_R11D
		}
		goto yystate0
	}
yyrule187: // zmm22
	{
		{
			lval.str = "zmm22"
			return TOKEN_REG_ZMM22
		}
		goto yystate0
	}
yyrule188: // zmm21
	{
		{
			lval.str = "zmm21"
			return TOKEN_REG_ZMM21
		}
		goto yystate0
	}
yyrule189: // zmm20
	{
		{
			lval.str = "zmm20"
			return TOKEN_REG_ZMM20
		}
		goto yystate0
	}
yyrule190: // es
	{
		{
			lval.str = "es"
			return TOKEN_REG_ES
		}
		goto yystate0
	}
yyrule191: // r11w
	{
		{
			lval.str = "r11w"
			return TOKEN_REG_R11W
		}
		goto yystate0
	}
yyrule192: // fs
	{
		{
			lval.str = "fs"
			return TOKEN_REG_FS
		}
		goto yystate0
	}
yyrule193: // ymm11
	{
		{
			lval.str = "ymm11"
			return TOKEN_REG_YMM11
		}
		goto yystate0
	}
yyrule194: // ymm10
	{
		{
			lval.str = "ymm10"
			return TOKEN_REG_YMM10
		}
		goto yystate0
	}
yyrule195: // ymm13
	{
		{
			lval.str = "ymm13"
			return TOKEN_REG_YMM13
		}
		goto yystate0
	}
yyrule196: // ymm12
	{
		{
			lval.str = "ymm12"
			return TOKEN_REG_YMM12
		}
		goto yystate0
	}
yyrule197: // ymm15
	{
		{
			lval.str = "ymm15"
			return TOKEN_REG_YMM15
		}
		goto yystate0
	}
yyrule198: // ymm14
	{
		{
			lval.str = "ymm14"
			return TOKEN_REG_YMM14
		}
		goto yystate0
	}
yyrule199: // ymm17
	{
		{
			lval.str = "ymm17"
			return TOKEN_REG_YMM17
		}
		goto yystate0
	}
yyrule200: // ymm16
	{
		{
			lval.str = "ymm16"
			return TOKEN_REG_YMM16
		}
		goto yystate0
	}
yyrule201: // ymm19
	{
		{
			lval.str = "ymm19"
			return TOKEN_REG_YMM19
		}
		goto yystate0
	}
yyrule202: // ymm18
	{
		{
			lval.str = "ymm18"
			return TOKEN_REG_YMM18
		}
		goto yystate0
	}
yyrule203: // eax
	{
		{
			lval.str = "eax"
			return TOKEN_REG_EAX
		}
		goto yystate0
	}
yyrule204: // zmm30
	{
		{
			lval.str = "zmm30"
			return TOKEN_REG_ZMM30
		}
		goto yystate0
	}
yyrule205: // zmm31
	{
		{
			lval.str = "zmm31"
			return TOKEN_REG_ZMM31
		}
		goto yystate0
	}
yyrule206: // zmm32
	{
		{
			lval.str = "zmm32"
			return TOKEN_REG_ZMM32
		}
		goto yystate0
	}
yyrule207: // sp
	{
		{
			lval.str = "sp"
			return TOKEN_REG_SP
		}
		goto yystate0
	}
yyrule208: // si
	{
		{
			lval.str = "si"
			return TOKEN_REG_SI
		}
		goto yystate0
	}
yyrule209: // zmm25
	{
		{
			lval.str = "zmm25"
			return TOKEN_REG_ZMM25
		}
		goto yystate0
	}
yyrule210: // eflags
	{
		{
			lval.str = "eflags"
			return TOKEN_REG_EFLAGS
		}
		goto yystate0
	}
yyrule211: // rep
	{
		{
			lval.str = "rep"
			return TOKEN_INST_PREFIX_REP
		}
		goto yystate0
	}
yyrule212: // repz
	{
		{
			lval.str = "repz"
			return TOKEN_INST_PREFIX_REPZ
		}
		goto yystate0
	}
yyrule213: // repe
	{
		{
			lval.str = "repe"
			return TOKEN_INST_PREFIX_REPE
		}
		goto yystate0
	}
yyrule214: // repne
	{
		{
			lval.str = "repne"
			return TOKEN_INST_PREFIX_REPNE
		}
		goto yystate0
	}
yyrule215: // repnz
	{
		{
			lval.str = "repnz"
			return TOKEN_INST_PREFIX_REPNZ
		}
		goto yystate0
	}
yyrule216: // lock
	{
		{
			lval.str = "lock"
			return TOKEN_INST_PREFIX_LOCK
		}
		goto yystate0
	}
yyrule217: // #.*$
	{
		/* ignore comment.. */
		goto yystate0
	}
yyrule218: // \<.*\>\:?
	{
		/*  ignore, gdb disassemble will put some comment information in `<>` */
		goto yystate0
	}
yyrule219: // [ \t\r]+
	{
		/* ignore */
		goto yystate0
	}
yyrule220: // [a-z][a-z0-9]+
	if true { // avoid go vet determining the below panic will not be reached
		{
			/* INST_MNEM */
			lval.str = string(this.buf)
			return INST_MNEM
		}
		goto yystate0
	}
	panic("unreachable")

yyabort: // no lexem recognized
	//
	// silence unused label errors for build and satisfy go vet reachability analysis
	//
	{
		if false {
			goto yyabort
		}
		if false {
			goto yystate0
		}
		if false {
			goto yystate1
		}
	}

	panic(fmt.Errorf("lex error; buf: %s; current: %d;", this.buf, this.current))
	return 0
}
